### ISSUE TITLE
Is it possible to swap existing npc models with this?

### ISSUE THREAD

**Issue by ENjoyBlue2021** [skawo/OoT-NPC-Maker#1]
I apologize in advance, this is probably the wrong place but I couldn't find any info on this.
Basically I want to swap models of existing npcs with another one.
Using files from here: https://modloader64.com/models.html
Could I use this tool to swap out the npcs if I somhow extract the needed files from the above links?

I tried reading into how n64 oot handles actor/objects buts its too much :(
Again, sorry for posting this here.

**Comment by skawo** [comment]
Not quite, but you could probably recreate the actor in question instead fairly easily with a changed model.

**Comment by ENjoyBlue2021** [comment]
Ok, thanks for the answer!
